# Generated by Django 5.1.5 on 2025-02-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('declined', 'Declined')], default='new', max_length=10),
        ),
    ]
