# Generated by Django 5.1.5 on 2025-02-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
