# Generated by Django 5.1.5 on 2025-02-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_registered_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
